// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgVEn10f17_j61IcVxfSDd5Q_az8xhg8',
    appId: '1:982006411920:web:081a1f1664f1af44be1e15',
    messagingSenderId: '982006411920',
    projectId: 'testingpolling-a3d03',
    authDomain: 'testingpolling-a3d03.firebaseapp.com',
    storageBucket: 'testingpolling-a3d03.appspot.com',
    measurementId: 'G-50JSBRWBBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz7c1JJKv1mQiOK7Cc7OXymxmTBT3DNYU',
    appId: '1:982006411920:android:54c824e36e6967dabe1e15',
    messagingSenderId: '982006411920',
    projectId: 'testingpolling-a3d03',
    storageBucket: 'testingpolling-a3d03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ne3PTqkazunVvBt-FCPgqHHMS4jeQBk',
    appId: '1:982006411920:ios:73fef27a80b84ef2be1e15',
    messagingSenderId: '982006411920',
    projectId: 'testingpolling-a3d03',
    storageBucket: 'testingpolling-a3d03.appspot.com',
    iosBundleId: 'com.example.teacherLiveClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ne3PTqkazunVvBt-FCPgqHHMS4jeQBk',
    appId: '1:982006411920:ios:73fef27a80b84ef2be1e15',
    messagingSenderId: '982006411920',
    projectId: 'testingpolling-a3d03',
    storageBucket: 'testingpolling-a3d03.appspot.com',
    iosBundleId: 'com.example.teacherLiveClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAgVEn10f17_j61IcVxfSDd5Q_az8xhg8',
    appId: '1:982006411920:web:7e0abe4d171e2b3dbe1e15',
    messagingSenderId: '982006411920',
    projectId: 'testingpolling-a3d03',
    authDomain: 'testingpolling-a3d03.firebaseapp.com',
    storageBucket: 'testingpolling-a3d03.appspot.com',
    measurementId: 'G-DFZT3WW3L8',
  );
}
